# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    #max-threads: 1000
    #min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /cms-migrate
  #address: 127.0.0.1

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #servlet:

logging:
  level: info
  level.com.yykt: info
  path: logs/
  file: cms-migrate.log
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.cms.migrate.model
